[settings]
os_layout = "qwerty-us"
tap_time  = 100

[macros]
arrow           = "->"
fat_arrow       = "=>"
double_colon    = "::"
five_down       = { key = "down_arrow", repeat = 5 }
five_up         = { key = "up_arrow", repeat = 5 }

bol             = "{left_command+left_arrow}"
eol             = "{left_command+right_arrow}"
app_switch      = "{left_command+tab}"                        # app switch
mission_ctrl    = "{left_control+up_arrow}"                   # mission control
spotlight       = "{left_command+spacebar}"
aero_monitor    = "{left_alt+left_shift+tab}"                 # aerospace monitor switch
delete_line     = "{home}{shift+down_arrow}{delete_or_backspace}"   # or {command+x} to yank

[layers.base]
caps_lock       = "delete_or_backspace"     # caps lock to delete, symmetric to return 
right_command   = "sym"                     # symbol layer trigger
right_alt       = "nav"                     # navigation layer trigger
left_control    = ["escape", "left_control"]
left_shift      = ["escape", "left_shift"]


[layers.nav]

# lpinky
caps_lock       = "$delete_line"
q               = "$aero_monitor"
a               = "$bol"           
# lannular
w               = "$app_switch"
s               = "left_arrow"
# lmiddle
e               = "up_arrow"
d               = "down_arrow"
# lindex
r               = "$mission_ctrl"
f               = "right_arrow"

t               = "display_brightness_increment"
g               = "$eol"
v               = "display_brightness_decrement"

# lthumb
# left_command    = "$spotlight" # conflict with doing "command+number"

# rindex
y               = "volume_increment"
h               = "mute"
n               = "volume_decrement"

u               = "7"
j               = "4"
m               = "1"
# rmiddle
i               = "8"
k               = "5"
comma           = "2"
# rannular
o               = "9"
l               = "6"
period          = "3"
# rpinky
semicolon       = "0"



[layers.sym]

### left hand: brackets optimized for finger rolls

# lpinky
q               = "{"
a               = "<"
# lannular
w               = "}" 
s               = ">" 
z               = "!"
# lmiddle
e               = "["                       
d               = "("
x               = "?"
# lindex
r               = "]"
f               = ")"
c               = "semicolon"

t               = "left_shift+4"           # $
g               = "$arrow"                 # ->
v               = "$double_colon"          # ::

### right hand: symbols

# lindex
y               = "%"
h               = "$fat_arrow"             # =>, right hand technically
n               = "@"

u               = "+"                       
j               = "_"
m               = "#"
# lmiddle
i               = "-"                       
k               = "="
comma           = "/"  
# lannular
o               = "*"
l               = "|" 
period          = "backslash"
# lpinky
p               = "^"
semicolon       = "&"   
slash           = "left_shift"
